In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/SenseTimeV4/data_SenseTime_A0_1.csv")

In [3]:
df

,start_timestamp,end_timestamp,error,start_image,end_image,start_image_index,end_image_index,num_images,brightness,contrast,...,rel_q_y,rel_q_z,rel_q_w,rel2_p_x,rel2_p_y,rel2_p_z,rel2_q_x,rel2_q_y,rel2_q_z,rel2_q_w
0,771831317667077,771834782667077,0.084064,771831316597066,771834783157066,572.0,676.0,104,0.558603,49.423820,...,NaN,NaN,NaN,-0.447410,0.534851,0.001289,0.146427,0.088654,0.036518,0.984564
1,771831350167077,771834817667077,0.092396,771831349929357,771834816489357,573.0,677.0,104,0.558561,49.251043,...,1.123979e-03,-3.442639e-04,0.999998,-0.450748,0.548536,-0.004367,0.146266,0.085293,0.033083,0.985006
2,771831382667077,771834817667077,0.103097,771831383261649,771834816489357,574.0,677.0,103,0.559005,49.123978,...,1.734723e-18,0.000000e+00,1.000000,-0.450574,0.546210,-0.005297,0.146622,0.079514,0.030970,0.985505
3,771831417667077,771834850167077,0.111860,771831416593993,771834849821649,575.0,678.0,103,0.558873,48.954828,...,7.108267e-04,-2.767288e-04,0.999999,-0.452344,0.560812,-0.009171,0.144940,0.076249,0.028726,0.986080
4,771831450167077,771834850167077,0.119352,771831449926284,771834849821649,576.0,678.0,102,0.559256,48.828622,...,5.204170e-18,0.000000e+00,1.000000,-0.452133,0.559719,-0.012128,0.144439,0.069993,0.025729,0.986700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044,771866115167077,771870482667077,0.020937,771866115526284,771870482058576,1616.0,1741.0,125,0.547727,46.707911,...,5.204170e-18,2.775558e-17,1.000000,0.188183,0.509312,-0.312394,-0.115706,-0.397121,-0.768905,0.487536
1045,771866147667077,771870482667077,0.019287,771866148858576,771870482058576,1617.0,1741.0,124,0.548562,46.607395,...,5.204170e-18,2.775558e-17,1.000000,0.199979,0.501611,-0.311320,-0.115724,-0.393553,-0.762321,0.500590
1046,771866182667077,771870482667077,0.024644,771866182190920,771870482058576,1618.0,1741.0,123,0.549480,46.515845,...,5.204170e-18,2.775558e-17,1.000000,0.217001,0.492310,-0.311084,-0.112768,-0.389878,-0.756026,0.513521
1047,771866215167077,771870482667077,0.028630,771866215523211,771870482058576,1619.0,1741.0,122,0.550468,46.433992,...,5.204170e-18,2.775558e-17,1.000000,0.226301,0.487616,-0.307402,-0.114385,-0.387721,-0.749108,0.524810
1048,771866247667077,771870482667077,0.028994,771866248855503,771870482058576,1620.0,1741.0,121,0.551503,46.361846,...,5.204170e-18,2.775558e-17,1.000000,0.237583,0.479880,-0.305509,-0.114416,-0.383872,-0.740582,0.539527

In [4]:
def select_columns(df):
    df['start_image_index'] = df['start_image_index'].astype(int)
    keep_cols = ['start_image_index', 'error',\
                 'brightness','entropy', 'num_images', 'min_corners', 'min_keypoints',\
                 'max_keypoints_diff', 'min_keypoint_dist','min_inliers',\
                 'localba_error', 'localba_visual_error', 'localba_inertial_error',\
                 'acc_magnitude',]
    df = df[keep_cols]

    return df

In [5]:
df = select_columns(df)
df

,start_image_index,error,brightness,entropy,num_images,min_corners,min_keypoints,max_keypoints_diff,min_keypoint_dist,min_inliers,localba_error,localba_visual_error,localba_inertial_error,acc_magnitude
0,572,0.084064,0.558603,7.294162,104,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,14.840896
1,573,0.092396,0.558561,7.291242,104,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.759345
2,574,0.103097,0.559005,7.288196,103,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.757799
3,575,0.111860,0.558873,7.285532,103,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.753009
4,576,0.119352,0.559256,7.282616,102,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.753571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1044,1616,0.020937,0.547727,7.199539,125,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775183
1045,1617,0.019287,0.548562,7.195558,124,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775900
1046,1618,0.024644,0.549480,7.191629,123,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.774772
1047,1619,0.028630,0.550468,7.187816,122,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775837
1048,1620,0.028994,0.551503,7.184244,121,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.777050

In [6]:
window_length = 48

In [21]:
label_df = df.loc[:, 'error'].copy().reset_index(drop=True).rolling(24).mean()
label_df[:50]

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23    0.094843
24    0.095173
25    0.095063
26    0.094492
27    0.093482
28    0.092365
29    0.091367
30    0.090106
31    0.089921
32    0.089550
33    0.089370
34    0.089153
35    0.089164
36    0.088997
37    0.088639
38    0.088814
39    0.089013
40    0.089242
41    0.089317
42    0.089304
43    0.089407
44    0.089523
45    0.089355
46    0.089299
47    0.088266
48    0.087025
49    0.086059
Name: error, dtype: float64

In [24]:
label_df.loc[:24] = df.loc[:24, 'error']
label_df[0:50]

0     0.084064
1     0.092396
2     0.103097
3     0.111860
4     0.119352
5     0.128820
6     0.135033
7     0.087674
8     0.096768
9     0.091544
10    0.094030
11    0.091530
12    0.099570
13    0.102934
14    0.090645
15    0.078245
16    0.076705
17    0.081522
18    0.084068
19    0.082346
20    0.082344
21    0.087274
22    0.085470
23    0.088938
24    0.091989
25    0.095063
26    0.094492
27    0.093482
28    0.092365
29    0.091367
30    0.090106
31    0.089921
32    0.089550
33    0.089370
34    0.089153
35    0.089164
36    0.088997
37    0.088639
38    0.088814
39    0.089013
40    0.089242
41    0.089317
42    0.089304
43    0.089407
44    0.089523
45    0.089355
46    0.089299
47    0.088266
48    0.087025
49    0.086059
Name: error, dtype: float64

In [25]:
label_df = label_df.loc[window_length:].copy().reset_index(drop=True)
label_df[0:50]

0     0.087025
1     0.086059
2     0.085157
3     0.084262
4     0.083088
5     0.081316
6     0.079484
7     0.078428
8     0.077081
9     0.075578
10    0.073882
11    0.071895
12    0.069712
13    0.067541
14    0.064506
15    0.062400
16    0.060156
17    0.057636
18    0.055296
19    0.053065
20    0.050698
21    0.048109
22    0.045583
23    0.043872
24    0.042399
25    0.040999
26    0.039441
27    0.037649
28    0.036197
29    0.034705
30    0.033549
31    0.032473
32    0.031743
33    0.031360
34    0.031374
35    0.031443
36    0.031545
37    0.031779
38    0.032164
39    0.032205
40    0.032304
41    0.032947
42    0.033379
43    0.033563
44    0.033922
45    0.034166
46    0.034252
47    0.034244
48    0.034070
49    0.033996
Name: error, dtype: float64

In [7]:
label_df = df.loc[window_length:, 'error'].copy().reset_index(drop=True)
label_df

0       0.062209
1       0.066574
2       0.067722
3       0.066137
4       0.064356
          ...
996     0.020937
997     0.019287
998     0.024644
999     0.028630
1000    0.028994
Name: error, Length: 1001, dtype: float64

In [8]:
window_number = 0
slide_df = df.iloc[0:window_length].copy().drop('error', axis=1)
slide_df = slide_df.assign(start_image_index = window_number)
for idx in range(window_length+1, len(df)):
    window_number +=1
    window_df = df.iloc[idx-window_length:idx].copy()
    window_df = window_df.assign(start_image_index = window_number)
    slide_df = pd.concat([slide_df, window_df], axis=0, ignore_index=True)

In [9]:
slide_df

,start_image_index,brightness,entropy,num_images,min_corners,min_keypoints,max_keypoints_diff,min_keypoint_dist,min_inliers,localba_error,localba_visual_error,localba_inertial_error,acc_magnitude,error
0,0,0.558603,7.294162,104,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,14.840896,NaN
1,0,0.558561,7.291242,104,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.759345,NaN
2,0,0.559005,7.288196,103,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.757799,NaN
3,0,0.558873,7.285532,103,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.753009,NaN
4,0,0.559256,7.282616,102,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.753571,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48043,1000,0.546985,7.203657,126,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.773883,0.020954
48044,1000,0.547727,7.199539,125,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775183,0.020937
48045,1000,0.548562,7.195558,124,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775900,0.019287
48046,1000,0.549480,7.191629,123,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.774772,0.024644
48047,1000,0.550468,7.187816,122,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775837,0.028630

In [10]:
1001*48

48048

In [11]:
slide_df

,start_image_index,brightness,entropy,num_images,min_corners,min_keypoints,max_keypoints_diff,min_keypoint_dist,min_inliers,localba_error,localba_visual_error,localba_inertial_error,acc_magnitude,error
0,0,0.558603,7.294162,104,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,14.840896,NaN
1,0,0.558561,7.291242,104,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.759345,NaN
2,0,0.559005,7.288196,103,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.757799,NaN
3,0,0.558873,7.285532,103,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.753009,NaN
4,0,0.559256,7.282616,102,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.753571,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48043,1000,0.546985,7.203657,126,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.773883,0.020954
48044,1000,0.547727,7.199539,125,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775183,0.020937
48045,1000,0.548562,7.195558,124,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775900,0.019287
48046,1000,0.549480,7.191629,123,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.774772,0.024644
48047,1000,0.550468,7.187816,122,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775837,0.028630

In [12]:
slide_df.loc[:, 'start_image_index'] += 99000000
slide_df

,start_image_index,brightness,entropy,num_images,min_corners,min_keypoints,max_keypoints_diff,min_keypoint_dist,min_inliers,localba_error,localba_visual_error,localba_inertial_error,acc_magnitude,error
0,99000000,0.558603,7.294162,104,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,14.840896,NaN
1,99000000,0.558561,7.291242,104,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.759345,NaN
2,99000000,0.559005,7.288196,103,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.757799,NaN
3,99000000,0.558873,7.285532,103,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.753009,NaN
4,99000000,0.559256,7.282616,102,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.753571,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48043,99001000,0.546985,7.203657,126,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.773883,0.020954
48044,99001000,0.547727,7.199539,125,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775183,0.020937
48045,99001000,0.548562,7.195558,124,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775900,0.019287
48046,99001000,0.549480,7.191629,123,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.774772,0.024644
48047,99001000,0.550468,7.187816,122,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775837,0.028630

In [13]:
slide_df['start_image_index'].unique()

array([99000000, 99000001, 99000002, ..., 99000998, 99000999, 99001000])

In [14]:
label_df.to_frame()

         error
0     0.062209
1     0.066574
2     0.067722
3     0.066137
4     0.064356
...        ...
996   0.020937
997   0.019287
998   0.024644
999   0.028630
1000  0.028994

[1001 rows x 1 columns]

In [15]:
slide_df=slide_df.set_index('start_image_index')
slide_df

,brightness,entropy,num_images,min_corners,min_keypoints,max_keypoints_diff,min_keypoint_dist,min_inliers,localba_error,localba_visual_error,localba_inertial_error,acc_magnitude,error
start_image_index,,,,,,,,,,,,,
99000000,0.558603,7.294162,104,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,14.840896,NaN
99000000,0.558561,7.291242,104,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.759345,NaN
99000000,0.559005,7.288196,103,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.757799,NaN
99000000,0.558873,7.285532,103,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.753009,NaN
99000000,0.559256,7.282616,102,1478.0,1001.0,7.0,0.99,51.0,6178.85,8706.26,42.4122,9.753571,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99001000,0.546985,7.203657,126,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.773883,0.020954
99001000,0.547727,7.199539,125,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775183,0.020937
99001000,0.548562,7.195558,124,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775900,0.019287
99001000,0.549480,7.191629,123,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.774772,0.024644
99001000,0.550468,7.187816,122,1543.0,1000.0,7.0,1.00,46.0,17527.90,18115.40,122.6910,9.775837,0.028630

In [ ]:
label_df = label_df.to_frame()
label_df = label_df.set_index(index)
label_df

In [ ]:
label_df.index